export const FRIENDLY_FIRE_ENABLED = false;

export const PROJECTILE_DEFAULT_RADIUS = 2.2;
export const ARROW_PROJECTILE_RADIUS = 2.2;
export const STONE_PROJECTILE_RADIUS = 2.9;
export const PROJECTILE_DEFAULT_MAX_LIFE = 3.2;
export const PROJECTILE_DEFAULT_DRAG = 0.012;

export const RANGED_ARMOR_REDUCTION_MULTIPLIER = 0.3;
export const STONE_ARMOR_REDUCTION_MULTIPLIER = 0.25;
export const RANGED_SHIELD_FRONT_MULTIPLIER = 0.7;
export const RANGED_REAR_MULTIPLIER = 1.45;
export const RANGED_FLANK_MULTIPLIER = 1.15;

export const ARCHER_MAX_LEAD_TIME = 0.9;
export const ARCHER_MOVING_SPEED_THRESHOLD = 32;
export const ARCHER_MOVING_SPREAD_MULTIPLIER = 1.6;
export const ARCHER_BASE_SPREAD_RADIANS = 0.26;

export const SKIRMISH_THREAT_FACTOR = 0.6;
export const SKIRMISH_RETREAT_DISTANCE = 120;
export const SKIRMISH_ADVANCE_SPEED_FACTOR = 0.82;
export const SKIRMISH_RETREAT_SPEED_FACTOR = 1.06;

export const MINIMAP_WIDTH = 230;
export const MINIMAP_HEIGHT = 145;
export const MINIMAP_MARGIN = 12;
