export const OBJECTIVE_BATTLE_HOLDOUT_CHANCE = 0.15;
export const OBJECTIVE_BATTLE_ESCORT_CHANCE = 0.15;
export const OBJECTIVE_BATTLE_CAPTURE_CHANCE = 0.7;

export const OBJECTIVE_ELITE_CAPTURE_CHANCE = 0.5;
export const OBJECTIVE_BOSS_CAPTURE_CHANCE = 0.4;

export const CAPTURE_SPEED_ELITE = 0.78;
export const CAPTURE_SPEED_BOSS = 0.62;

export const HOLDOUT_DURATION_SECONDS = 120;
export const HOLDOUT_WAVE_INTERVAL_SECONDS = 25;
export const HOLDOUT_MAX_WAVES = 4;
export const HOLDOUT_WAVE_MIN_SQUADS = 1;
export const HOLDOUT_WAVE_MAX_SQUADS = 2;
export const HOLDOUT_WAVE_BASE_SIZE = 17;
export const HOLDOUT_WAVE_SIZE_PER_DIFFICULTY = 2;
export const HOLDOUT_WAVE_SIZE_PER_WAVE = 1;

export const ESCORT_TIME_LIMIT_SECONDS = 180;
export const ESCORT_CARAVAN_HP = 480;
export const ESCORT_CARAVAN_SPEED = 62;
export const ESCORT_CARAVAN_RADIUS = 8;
export const ESCORT_EXIT_RADIUS = 120;
export const ESCORT_EXIT_HOLD_SECONDS = 3;
