import type {
  NodesTuningContent,
  ObjectivesTuningContent,
  PerksContent,
  ScenariosContent,
  UnitsContent,
  UpgradePathsContent,
} from './ContentTypes';

export const DEFAULT_UNITS_CONTENT: UnitsContent = {
  contentVersion: '1.0.0',
  fallbackArchetypeId: 'infantry',
  units: [
    {
      id: 'infantry',
      name: 'Infantry',
      recruitable: true,
      tags: ['infantry', 'shield'],
      tiers: {
        '1': {
          hp: 100,
          moveSpeed: 90,
          attackDamage: 10,
          attackRate: 1,
          meleeRange: 13,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 4,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '2': {
          hp: 114,
          moveSpeed: 92.7,
          attackDamage: 11.2,
          attackRate: 1,
          meleeRange: 13,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 4.48,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '3': {
          hp: 128,
          moveSpeed: 94.5,
          attackDamage: 12.2,
          attackRate: 1,
          meleeRange: 13,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 4.96,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
      },
    },
    {
      id: 'spearmen',
      name: 'Spearmen',
      recruitable: true,
      tags: ['infantry', 'spear'],
      tiers: {
        '1': {
          hp: 95,
          moveSpeed: 85,
          attackDamage: 9,
          attackRate: 1,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 3,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '2': {
          hp: 108.3,
          moveSpeed: 87.55,
          attackDamage: 10.08,
          attackRate: 1,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 3.36,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '3': {
          hp: 121.6,
          moveSpeed: 89.25,
          attackDamage: 10.98,
          attackRate: 1,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 3.72,
          mass: 1,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
      },
    },
    {
      id: 'cavalry',
      name: 'Cavalry',
      recruitable: true,
      tags: ['cavalry', 'heavy'],
      tiers: {
        '1': {
          hp: 120,
          moveSpeed: 140,
          attackDamage: 11,
          attackRate: 0.9,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 5,
          mass: 1.4,
          chargePower: 2.2,
          chargeMinSpeed: 110,
        },
        '2': {
          hp: 136.8,
          moveSpeed: 144.2,
          attackDamage: 12.32,
          attackRate: 0.9,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 5.6,
          mass: 1.4,
          chargePower: 2.2,
          chargeMinSpeed: 110,
        },
        '3': {
          hp: 153.6,
          moveSpeed: 147,
          attackDamage: 13.42,
          attackRate: 0.9,
          meleeRange: 14,
          rangedDamage: 0,
          rangedRange: 0,
          projectileSpeed: 0,
          projectileGravity: 0,
          rangedCooldown: 0,
          accuracy: 1,
          armor: 6.2,
          mass: 1.4,
          chargePower: 2.2,
          chargeMinSpeed: 110,
        },
      },
    },
    {
      id: 'archers',
      name: 'Archers',
      recruitable: true,
      tags: ['archer', 'light'],
      tiers: {
        '1': {
          hp: 75,
          moveSpeed: 95,
          attackDamage: 6,
          attackRate: 1.25,
          meleeRange: 12,
          rangedDamage: 7.2,
          rangedRange: 390,
          projectileSpeed: 340,
          projectileGravity: 150,
          rangedCooldown: 0,
          accuracy: 0.78,
          armor: 1,
          mass: 0.9,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '2': {
          hp: 85.5,
          moveSpeed: 97.85,
          attackDamage: 6.72,
          attackRate: 1.25,
          meleeRange: 12,
          rangedDamage: 7.99,
          rangedRange: 390,
          projectileSpeed: 340,
          projectileGravity: 150,
          rangedCooldown: 0,
          accuracy: 0.78,
          armor: 1.12,
          mass: 0.9,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
        '3': {
          hp: 96,
          moveSpeed: 99.75,
          attackDamage: 7.32,
          attackRate: 1.25,
          meleeRange: 12,
          rangedDamage: 8.64,
          rangedRange: 390,
          projectileSpeed: 340,
          projectileGravity: 150,
          rangedCooldown: 0,
          accuracy: 0.78,
          armor: 1.24,
          mass: 0.9,
          chargePower: 1,
          chargeMinSpeed: 999,
        },
      },
    },
  ],
  startingArmy: {
    gold: 55,
    supplies: 35,
    recruits: 12,
    squads: [
      { archetypeId: 'infantry', size: 30, tier: 1, name: 'Vanguard' },
      { archetypeId: 'spearmen', size: 28, tier: 1, name: 'Pikes' },
      { archetypeId: 'archers', size: 24, tier: 1, name: 'Bowline' },
    ],
  },
};

export const DEFAULT_UPGRADES_CONTENT: UpgradePathsContent = {
  contentVersion: '1.0.0',
  maxTier: 3,
  defaultUpgradeCost: 0,
  paths: {
    infantry: {
      nextTierByTier: { '1': 2, '2': 3 },
      costByTier: { '2': 0, '3': 0 },
    },
    spearmen: {
      nextTierByTier: { '1': 2, '2': 3 },
      costByTier: { '2': 0, '3': 0 },
    },
    cavalry: {
      nextTierByTier: { '1': 2, '2': 3 },
      costByTier: { '2': 0, '3': 0 },
    },
    archers: {
      nextTierByTier: { '1': 2, '2': 3 },
      costByTier: { '2': 0, '3': 0 },
    },
  },
};

export const DEFAULT_PERKS_CONTENT: PerksContent = {
  version: 'perks_v1',
  rewardRules: {
    everyNNodes: 3,
    choices: 3,
  },
  perks: [
    {
      id: 'iron_discipline',
      name: 'Iron Discipline',
      desc: 'Rout slower and morale recovers faster.',
      rarity: 'common',
      mods: {
        moraleRegenMult: 1.25,
        routThresholdAdd: -5,
      },
    },
    {
      id: 'tight_ranks',
      name: 'Tight Ranks',
      desc: 'Improved cohesion with denser lines.',
      rarity: 'common',
      mods: {
        cohesionMult: 1.25,
        formationSpacingMult: 0.9,
      },
    },
    {
      id: 'blessed_arrows',
      name: 'Blessed Arrows',
      desc: 'Archers fire truer and faster shots.',
      rarity: 'rare',
      mods: {
        rangedAccuracyAdd: 0.08,
        projectileSpeedMult: 1.15,
      },
    },
    {
      id: 'thunder_charge',
      name: 'Thunder Charge',
      desc: 'Charge impact increases with faster resets.',
      rarity: 'rare',
      mods: {
        chargePowerMult: 1.2,
        chargeCooldownMult: 0.85,
      },
    },
    {
      id: 'brace',
      name: 'Brace',
      desc: 'Spear formations punish cavalry charges harder.',
      rarity: 'common',
      mods: {
        spearCounterDamageMult: 1.25,
      },
    },
    {
      id: 'war_drums',
      name: 'War Drums',
      desc: 'Battle rhythm reduces morale shock.',
      rarity: 'common',
      mods: {
        moraleLossMult: 0.9,
      },
    },
    {
      id: 'swift_muster',
      name: 'Swift Muster',
      desc: 'Faster redeployments with looser staging.',
      rarity: 'common',
      mods: {
        formationSpacingMult: 1.1,
        cohesionMult: 0.95,
        moveSpeedMult: 1.08,
      },
    },
    {
      id: 'siegecraft',
      name: 'Siegecraft',
      desc: 'Capture progress advances more quickly.',
      rarity: 'rare',
      mods: {
        captureRateMult: 1.15,
      },
    },
    {
      id: 'hardened_steel',
      name: 'Hardened Steel',
      desc: 'Armor holds better under pressure.',
      rarity: 'rare',
      mods: {
        armorEffectivenessMult: 1.1,
      },
    },
    {
      id: 'field_medic',
      name: 'Field Medic',
      desc: 'Recover extra recruits from post-battle survivors.',
      rarity: 'common',
      mods: {
        fieldMedicRecruitsPerCasualty: 0.12,
      },
    },
  ],
};

export const DEFAULT_OBJECTIVES_CONTENT: ObjectivesTuningContent = {
  contentVersion: '1.0.0',
  selectionWeightsByNodeType: {
    BATTLE: {
      CAPTURE: 0.55,
      ASSASSINATE: 0.15,
      HOLDOUT: 0.15,
      ESCORT: 0.15,
    },
    ELITE: {
      CAPTURE: 0.5,
      ASSASSINATE: 0.5,
      HOLDOUT: 0,
      ESCORT: 0,
    },
    BOSS: {
      CAPTURE: 0.4,
      ASSASSINATE: 0.6,
      HOLDOUT: 0,
      ESCORT: 0,
    },
  },
  capture: {
    radius: 240,
    baseGainRate: 0.8,
    contestedDecayRate: 0.35,
    opposingProgressDrainFactor: 0.45,
    speedMultiplierByNodeType: {
      BATTLE: 1,
      ELITE: 0.78,
      BOSS: 0.62,
    },
  },
  holdout: {
    durationSeconds: 120,
    waveIntervalSeconds: 25,
    maxWaves: 4,
    zoneRadius: 180,
    waveMinSquads: 1,
    waveMaxSquads: 2,
    waveBaseSize: 17,
    waveRandomSizeMaxAdd: 4,
    waveSizePerDifficulty: 2,
    waveSizePerWave: 1,
    waveArchetypes: ['infantry', 'spearmen', 'cavalry', 'archers'],
  },
  escort: {
    timeLimitSeconds: 180,
    caravanHp: 480,
    caravanSpeed: 62,
    caravanRadius: 8,
    exitRadius: 120,
    exitHoldSeconds: 3,
    startX: 260,
    exitXPadding: 220,
    startJitterY: 180,
    exitJitterY: 220,
  },
};

export const DEFAULT_NODES_CONTENT: NodesTuningContent = {
  contentVersion: '1.0.0',
  mapGeneration: {
    minNodes: 18,
    maxNodes: 24,
    layerCountMin: 5,
    layerCountMax: 6,
    middleLayerMin: 3,
    middleLayerMax: 5,
    middleLayerCap: 6,
    linkExtraChance: 0.35,
    nodeJitterY: 18,
  },
  nodeTypeWeightsByDepth: [
    {
      depthMin: 0,
      depthMax: 3,
      weights: {
        BATTLE: 0.54,
        SHOP: 0.16,
        RECRUIT: 0.13,
        REST: 0.13,
        ELITE: 0.04,
      },
    },
    {
      depthMin: 4,
      depthMax: 8,
      weights: {
        BATTLE: 0.5,
        SHOP: 0.12,
        RECRUIT: 0.12,
        REST: 0.12,
        ELITE: 0.14,
      },
    },
    {
      depthMin: 9,
      depthMax: 99,
      weights: {
        BATTLE: 0.46,
        SHOP: 0.1,
        RECRUIT: 0.1,
        REST: 0.1,
        ELITE: 0.24,
      },
    },
  ],
  rewardsByNodeType: {
    BATTLE: {
      gold: { min: 30, max: 52 },
      recruits: { min: 5, max: 10 },
      supplies: { min: 0, max: 2 },
    },
    SHOP: {
      gold: { min: 0, max: 0 },
      recruits: { min: 0, max: 0 },
      supplies: { min: 0, max: 0 },
    },
    RECRUIT: {
      gold: { min: 0, max: 0 },
      recruits: { min: 7, max: 14 },
      supplies: { min: 0, max: 0 },
    },
    REST: {
      gold: { min: 0, max: 0 },
      recruits: { min: 0, max: 0 },
      supplies: { min: 8, max: 16 },
    },
    ELITE: {
      gold: { min: 45, max: 70 },
      recruits: { min: 8, max: 13 },
      supplies: { min: 1, max: 4 },
    },
    BOSS: {
      gold: { min: 60, max: 80 },
      recruits: { min: 10, max: 15 },
      supplies: { min: 2, max: 6 },
    },
  },
  shop: {
    sizeUpgradeCost: 35,
    sizeUpgradeAmount: 5,
    suppliesCost: 22,
    suppliesAmount: 20,
  },
  recruit: {
    baseRecruits: 9,
    recruitsPerDifficulty: 2,
    recruitsBonusCap: 6,
    discountHireCost: 15,
    discountSizeMin: 18,
    discountSizeMax: 22,
  },
  rest: {
    suppliesGain: 12,
    restBonusBattles: 1,
  },
};

export const DEFAULT_SCENARIOS_CONTENT: ScenariosContent = {
  contentVersion: '1.0.0',
  objectivePowerScale: {
    CAPTURE: 1,
    ASSASSINATE: 1,
    HOLDOUT: 0.72,
    ESCORT: 0.9,
  },
  templatesByNodeType: {
    BATTLE: [
      {
        depthMin: 0,
        depthMax: 5,
        templates: [
          {
            id: 'battle_early_a',
            squads: [
              { archetypeId: 'infantry', tier: 1, size: 24 },
              { archetypeId: 'spearmen', tier: 1, size: 22 },
              { archetypeId: 'archers', tier: 1, size: 20 },
            ],
          },
          {
            id: 'battle_early_b',
            squads: [
              { archetypeId: 'infantry', tier: 1, size: 26 },
              { archetypeId: 'cavalry', tier: 1, size: 18 },
              { archetypeId: 'archers', tier: 1, size: 20 },
            ],
          },
        ],
      },
      {
        depthMin: 6,
        depthMax: 10,
        templates: [
          {
            id: 'battle_mid_a',
            squads: [
              { archetypeId: 'infantry', tier: 2, size: 26 },
              { archetypeId: 'spearmen', tier: 2, size: 24 },
              { archetypeId: 'archers', tier: 1, size: 22 },
            ],
          },
          {
            id: 'battle_mid_b',
            squads: [
              { archetypeId: 'infantry', tier: 2, size: 24 },
              { archetypeId: 'cavalry', tier: 2, size: 20 },
              { archetypeId: 'archers', tier: 2, size: 22 },
            ],
          },
        ],
      },
      {
        depthMin: 11,
        depthMax: 99,
        templates: [
          {
            id: 'battle_late_a',
            squads: [
              { archetypeId: 'infantry', tier: 2, size: 28 },
              { archetypeId: 'spearmen', tier: 3, size: 24 },
              { archetypeId: 'archers', tier: 2, size: 24 },
            ],
          },
          {
            id: 'battle_late_b',
            squads: [
              { archetypeId: 'infantry', tier: 3, size: 26 },
              { archetypeId: 'cavalry', tier: 3, size: 20 },
              { archetypeId: 'archers', tier: 2, size: 24 },
            ],
          },
        ],
      },
    ],
    ELITE: [
      {
        depthMin: 0,
        depthMax: 6,
        templates: [
          {
            id: 'elite_early_a',
            squads: [
              { archetypeId: 'infantry', tier: 2, size: 28 },
              { archetypeId: 'cavalry', tier: 2, size: 22 },
              { archetypeId: 'archers', tier: 2, size: 20 },
            ],
          },
          {
            id: 'elite_early_b',
            squads: [
              { archetypeId: 'spearmen', tier: 2, size: 28 },
              { archetypeId: 'infantry', tier: 2, size: 28 },
              { archetypeId: 'archers', tier: 2, size: 20 },
            ],
          },
        ],
      },
      {
        depthMin: 7,
        depthMax: 99,
        templates: [
          {
            id: 'elite_late_a',
            squads: [
              { archetypeId: 'infantry', tier: 3, size: 30 },
              { archetypeId: 'cavalry', tier: 3, size: 24 },
              { archetypeId: 'archers', tier: 2, size: 22 },
            ],
          },
          {
            id: 'elite_late_b',
            squads: [
              { archetypeId: 'spearmen', tier: 3, size: 30 },
              { archetypeId: 'infantry', tier: 3, size: 28 },
              { archetypeId: 'archers', tier: 3, size: 22 },
            ],
          },
        ],
      },
    ],
    BOSS: [
      {
        depthMin: 0,
        depthMax: 99,
        templates: [
          {
            id: 'boss_a',
            squads: [
              { archetypeId: 'infantry', tier: 3, size: 38 },
              { archetypeId: 'cavalry', tier: 3, size: 28 },
              { archetypeId: 'spearmen', tier: 3, size: 34 },
            ],
          },
          {
            id: 'boss_b',
            squads: [
              { archetypeId: 'infantry', tier: 3, size: 36 },
              { archetypeId: 'archers', tier: 3, size: 30 },
              { archetypeId: 'cavalry', tier: 3, size: 26 },
            ],
          },
        ],
      },
    ],
  },
};
